{% set name = "Newspaper3k" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/newspaper3k-{{ version }}.tar.gz
  sha256: 9f1bd3e1fb48f400c715abf875cc7b0a67b7ddcd87f50c9aeeb8fcbbbd9004fb

build:
  number: 4
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - beautifulsoup4 >=4.4.1
    - cssselect >=0.9.2
    - feedfinder2 >=0.0.4
    - feedparser >=5.2.1
    - jieba3k >=0.35.1
    - lxml >=3.6.0
    - nltk >=3.2.1
    - pillow >=3.3.0
    - python >={{ python_min }}
    - python-dateutil >=2.5.3
    - pyyaml >=3.11
    - requests >=2.10.0
    - tinysegmenter ==0.3
    - tldextract >=2.0.1

test:
  imports:
    - newspaper
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/codelucas/newspaper/
  summary: Simplified python article discovery & extraction.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - GOOSE-LICENSE.txt
  doc_url: https://newspaper.readthedocs.io/en/latest
  dev_url: https://github.com/codelucas/newspaper

extra:
  recipe-maintainers:
    - ganeshhubale
    - BastianZim
