{% set name = "newspaper3k" %}
{% set version = "0.2.7" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "20c04512b4c1634c514dcf4913962a7f886d2c53757855d43487e59e486cac76" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]
  
requirements:
  build:
    - python
    - setuptools
  
  run:
    - python
    - beautifulsoup4 >=4.4.1
    - pillow >=3.3.0
    - pyyaml >=3.11
    - cssselect >=0.9.2
    - lxml >=3.6.0
    - nltk >=3.2.1
    - requests >=2.10.0
    - feedparser >=5.2.1
    - tldextract >=2.0.1
    - feedfinder2 >=0.0.4
    - jieba3k >=0.35.1
    - python-dateutil >=2.5.3

test:
  imports:
    - newspaper

about:
  home: https://github.com/codelucas/newspaper/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified python article discovery & extraction.
  description: "Newspaper3k: Article scraping & curation."
    
  doc_url: 'https://newspaper.readthedocs.io/en/latest/'
  dev_url: 'https://github.com/codelucas/newspaper/'
  

extra:
  recipe-maintainers: 
  - ganeshhubale
     
  
