{% set version = "0.2.8" %}

package:
  name: newspaper3k
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/newspaper3k/newspaper3k-{{ version }}.tar.gz
  sha256: 9f1bd3e1fb48f400c715abf875cc7b0a67b7ddcd87f50c9aeeb8fcbbbd9004fb

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py2k]
  
requirements:
  host:
    - python
    - pip  
  run:
    - python
    - beautifulsoup4 >=4.4.1
    - pillow >=3.3.0
    - pyyaml >=3.11
    - cssselect >=0.9.2
    - lxml >=3.6.0
    - nltk >=3.2.1
    - requests >=2.10.0
    - feedparser >=5.2.1
    - tldextract >=2.0.1
    - feedfinder2 >=0.0.4
    - jieba3k >=0.35.1
    - python-dateutil >=2.5.3

test:
  imports:
    - newspaper

about:
  home: https://github.com/codelucas/newspaper/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified python article discovery & extraction.
  description: "Newspaper3k: Article scraping & curation"
    
  doc_url: https://newspaper.readthedocs.io/en/latest
  dev_url: https://github.com/codelucas/newspaper
  

extra:
  recipe-maintainers: 
  - ganeshhubale
     
  
