appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: H5FCjvMUzSLVJIKx8iCpdJKU7nJ3pILcRIj6IfaJHAccA+hRzcLP3gc2r4eS+9tcHUWkfxwf/vaTm4x8mWkRHFETaQbnsMIxPPwLH7KsOotX/C38hk0ie1w/lSX7H1xyE9XohZGGeAmEKgME4CqrC+1f4+EaKu4fFXbsXFwrLVUu+WXVkxC+SuxFcA2fiBS8LIVz1OsMHZto+Hq9pkuWNSlCHlvwkSHY5ql+V9Ie9YmbO+9D+oXOyaGo9Svo09ZVjWTbMrt5bmTzAzCjwGSKrQfuboemV6f66veiLchbmHQtsZqusLoSUM4o8tODRNGzgWR3by5Qfw1TjHOICwqILB7s8o42P5s5hHDLFxHNva6+yaghExt/AELvEY35ktlGWLbnOXin3jmiAyWdQFdW00hE+UCA0xZpKuHgGqrOKWMFuv/KyzU/kkNyC0EI+mtHTSZyL3eks4xjmVCF1h9Mao+B20tAy4mWgHIc60Auw2wq1oHBnrXJvcycpPhSAwBO3UoLb4G/virHtZt83Gwwof90IVaXTcaNqyK22EPWW3yKEN1EWBKGzP1Aze2y1Jyf9qfp/DquUCiEtMAO+FC8nwpWtHy7dNDNjkd8yllNIcx8/A7MmmOPP2L1mRRhjLVRocQ0dt8VvrtPnqWtfhnF/QIGhYFbOR7sfvrbtp8bx+o=}
provider:
  win: azure
conda_forge_output_validation: true
